{% set name = "hydrosignatures" %}
{% set version = "0.19.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 457dfe4cbe32504418780978f104c260d0a57bb0cbf25ef25329eaa0fb9652a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2
    - pandas >=1.0
    - scipy
    - xarray >=2023.03.0

test:
  imports:
    - hydrosignatures
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyriver/hydrosignatures
  summary: A collection of tools for computing hydrological signatures
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.hyriver.io/

extra:
  recipe-maintainers:
    - cheginit
